name: Update README
on:
  issues: {}
  push:
    branches: [master]
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Update README file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          node << 'EOF'
            const fs = require('fs')
            const { execSync } = require('child_process')
            const query = `query QueryIssues { 
              repository(owner: "dtinth", name: "github-actions-snippets") {
                issues(first: 100, labels: ["snippet"]) {
                  nodes {
                    title
                    author {
                      login
                    }
                    body
                    number
                    url
                    reactionGroups {
                      content
                      users {
                        totalCount
                      }
                    }
                  }
                }
              }
            }`
            const input = JSON.stringify({ query })
            const countReactions = (issue, name) => {
              const found = issue.reactionGroups.find(g => g.content === name)
              return found && found.users.totalCount || 0
            }
            const score = issue => {
              return countReactions(issue, 'THUMBS_UP') - countReactions(issue, 'THUMBS_DOWN')
            }
            const issues = JSON.parse(String(execSync(`curl -H "Authorization: Bearer ${process.env.GITHUB_TOKEN}" -X POST -d @- https://api.github.com/graphql`, { input })))
              .data.repository.issues.nodes
              .sort((a, b) => score(b) - score(a))
            const contents = issues
              .map(issue => {
                const m = issue.body.replace(/\r\n|\r/g, '\n').match(/^\s*(\w[^]*?\n```yaml\n[^]*?\n```)/)
                if (!m) {
                  console.log(`::warning::Issue ${issue.number} body text not recognized, skipping`)
                  return
                }
                return {
                  title: issue.title,
                  body: m[1],
                  number: issue.number,
                  author: issue.author.login,
                  score: score(issue),
                }
              })
              .filter(row => row)
              .map(row => {
                return [
                  `## ${row.title}`,
                  `${row.body}`,
                ].join('\n')
              }).join('\n\n')
            const readme = fs.readFileSync('README.md', 'utf8')
            const outputReadme = readme.replace(/<!-- begin autogen (\w+) -->([^]*?)<!-- end autogen \1 -->/, () => {
              const hash = require('crypto').createHash('sha256').update(contents).digest('hex')
              return `<!-- begin autogen ${hash} -->\n\n${contents}\n\n<!-- end autogen ${hash} -->`
            })
            if (readme !== outputReadme) {
              fs.writeFileSync('README.md', outputReadme)
            }
          EOF
      - name: Push changes back to GitHub
        env:
          GIT_COMMITTER_NAME: Janitor
          GIT_AUTHOR_NAME: Janitor
          EMAIL: repository-janitor[bot]@users.noreply.github.com
        run: |
          git add --all \
            && git commit -m "Update contents from GitHub Issues @ $(node -p 'new Date().toJSON()')" \
            || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" "$GITHUB_REF"
