name: Update README
on:
  issues: {}
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Update README file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          node << 'EOF'
            const fs = require('fs')
            const { execSync } = require('child_process')
            console.log('Hello world!')
          EOF
